export enum Type {
    Bug = 6,
    Dark = 16,
    Dragon = 15,
    Electric = 12,
    Fairy = 18,
    Fighting = 1,
    Fire = 9,
    Flying = 2,
    Ghost = 7,
    Grass = 11,
    Ground = 4,
    Ice = 14,
    Normal = 0,
    Poison = 3,
    Psychic = 13,
    Rock = 5,
    Steel = 8,
    Water = 10
}
